name: maven
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  it-test:
    name: Build Integrations
    strategy:
      matrix:
        os-integration: [ubuntu-20.04]
        java: [17]
    runs-on: ${{ matrix.os-integration }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: mvn clean install -Pinvoker --errors --batch-mode
